if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P0f9f3e0"
    echo -en "\x1b]P1aa172a"
    echo -en "\x1b]P237892d"
    echo -en "\x1b]P3cd9e1d"
    echo -en "\x1b]P4937abc"
    echo -en "\x1b]P5dd6d76"
    echo -en "\x1b]P6297f88"
    echo -en "\x1b]P75d4c3b"
    echo -en "\x1b]P8f9e6c2"
    echo -en "\x1b]P98e0013"
    echo -en "\x1b]PA127d06"
    echo -en "\x1b]PBa9800d"
    echo -en "\x1b]PC7b659e"
    echo -en "\x1b]PDc94f59"
    echo -en "\x1b]PE00727f"
    echo -en "\x1b]PF413324"
    clear
fi
