background: {{base}}
foreground: {{text}}

color0: {{overlay}}
color1: {{accent01}}
color2: {{accent02}}
color3: {{accent03}}
color4: {{accent04}}
color5: {{accent05}}
color6: {{accent06}}
color7: {{text}}

color8: {{high}}
color9: {{bright01}}
color10: {{bright02}}
color11: {{bright03}}
color12: {{bright04}}
color13: {{bright05}}
color14: {{bright06}}
color15: {{light}}
