if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P0{{base}}"
    echo -en "\x1b]P1{{accent01}}"
    echo -en "\x1b]P2{{accent02}}"
    echo -en "\x1b]P3{{accent03}}"
    echo -en "\x1b]P4{{accent04}}"
    echo -en "\x1b]P5{{accent05}}"
    echo -en "\x1b]P6{{accent06}}"
    echo -en "\x1b]P7{{text}}"
    echo -en "\x1b]P8{{overlay}}"
    echo -en "\x1b]P9{{bright01}}"
    echo -en "\x1b]PA{{bright02}}"
    echo -en "\x1b]PB{{bright03}}"
    echo -en "\x1b]PC{{bright04}}"
    echo -en "\x1b]PD{{bright05}}"
    echo -en "\x1b]PE{{bright06}}"
    echo -en "\x1b]PF{{light}}"
    clear
fi
