if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P0{{base}}"
    echo -en "\x1b]P1{{miko}}"
    echo -en "\x1b]P2{{yorishige}}"
    echo -en "\x1b]P3{{mima}}"
    echo -en "\x1b]P4{{tokiyuki}}"
    echo -en "\x1b]P5{{ayako}}"
    echo -en "\x1b]P6{{shizuku}}"
    echo -en "\x1b]P7{{text}}"
    echo -en "\x1b]P8{{overlay}}"
    echo -en "\x1b]P9{{taisha}}"
    echo -en "\x1b]PA{{suwa}}"
    echo -en "\x1b]PB{{sasaki}}"
    echo -en "\x1b]PC{{hojo}}"
    echo -en "\x1b]PD{{mochizuki}}"
    echo -en "\x1b]PE{{kami}}"
    echo -en "\x1b]PF{{light}}"
    clear
fi
